# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20190117_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
